### ISSUE TITLE
Candy identification broke Pokemon identification

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#129]
I'm on a fairly [recent commit](https://github.com/farkam135/GoIV/commit/99a1bf7b1f2b8f515c1b2201c86bbc2e7fe55fa0) for this post. A lot of pokemon are being recognized as the lowest devolutions that aren't even close to the fully evolved names.

* Victreebel is being recognized as bellsprout
* Primeape as Mankey
* Vileplume as Oddish.

I think this needs to be fixed before the next release.

**Comment by Blaisorblade** [comment]
I tried to improve things with https://github.com/farkam135/GoIV/pull/123, but that wasn't enough because of OCR errors—see #120.

I don't have those Pokemons, so it'd be good if somebody having them set a breakpoint in `Pokefly.showInfoLayout`, looked at what happens and posted the OCRed names.

Relatedly, #130 is about reducing the cost for misrecognition.

------
In case you are interested/have time to try debugging, resuming our convo: Why did Android Studio refuse to install the app—can you try and post the exact error? I had it once because (it told me) I had to first uninstall the existing app.
BTW, I'm using Android Studio 2.1.3.

**Comment by sarav** [comment]
The candy name based detection logic was very broken. I fixed it in #131 

Beedrill is a separate issue. OCR just does badly and make the name length match with Weedle instead of Beedrill.

**Comment by mattaereal** [comment]
Trying with Gloom, with latest repo, debugging `showInfoLayout`. 

`
candyName: Oddish
pokemonName: Gloom
`

But when the pop up appears with the pokemon name, Oddish prevails.

**Comment by mattaereal** [comment]
The `levenshteinDistance` is failing, or something is happening inside the for loop at PokeFly.getPossiblePokemon.

When iterating through the pokemon list, it stucks with number 43 (Oddish), and number 44 (Gloom) gets passed by. This has to do with the distance calculation. I'm still debugging.

**Comment by mattaereal** [comment]
I think I found the bug.

possiblePoke = {43, 0} // Gloom
possibleCandy = {42, 0} // Oddish

```

            if (possiblePoke[1] < possibleCandy[1]) {
                pokemonList.setSelection(possiblePoke[0]);
            } else {
                pokemonList.setSelection(possibleCandy[0]);
            }

```

I still don't know why this information is in lists. But, there's always a comparison between two 0s. It should be accessing the first part of the array [0], where the numbers 42, and 43 are. If possiblePoke is bigger, then it must be an evolution, and then that one should be set.

But I repeat, I still don't know why this information comes in lists, but the error here is a comparison between 2 0s, making it always go for the candyName.

**Comment by mattaereal** [comment]
I edited the logic to this one to continue debugging, I'll think of a better one later. Maybe you could guys help me out?

```
            pokemonList.setSelection(possibleCandy[0]);
            if (possiblePoke[1] == possibleCandy[1]) {
                if (possiblePoke[0] > possibleCandy[0]) {
                    pokemonList.setSelection(possiblePoke[0]);
                }
            }
```

I'm setting by default the pokemon name to the candy name since it's always the safer to assume, since you can't miss. If both candyName and pokemonName are found, you should always stick by your pokemonName (unless an user renamed an Oddish evolution like Gloom to Snorlax, for example, but we can't do anything to prevent users from committing such ridiculous things). Otherwise, stick with your candyName and let user pick from the dropdown list the nearest evolution.

**Comment by Blaisorblade** [comment]
@mattaereal For the particular scenario you describe, wouldn't `if (possiblePoke[1] <= possibleCandy[1])` be a simpler fix?
Meanwhile, this code is also being changed by #131.

**Comment by mattaereal** [comment]
Yes, it would be, I was not understanding the distance calculation until a few minutes ago.

**Comment by mattaereal** [comment]
Should we ignore this issue and continue with #131 ?

**Comment by Blaisorblade** [comment]
I like #131 over the current logic, but it'd probably be good to get more testing on it.

**Comment by mattaereal** [comment]
I asked because I haven't seen 131 yet. Gonna fetch and create a branch for that pull request and start posting my findings there.

**Comment by mattaereal** [comment]
I can confirm this is fixed on #131.

**Comment by sarav** [comment]
Btw, what case does candy name actually help? Is it just a hypothesis that it would help? Or has it actually helped some case? I want to confirm OCR for candy actually does better sometimes -- otherwise, a lot of trouble for nothing.

**Comment by Blaisorblade** [comment]
> Btw, what case does candy name actually help?

Some users like to rename pokemons to whatever; feature is discussed in https://github.com/farkam135/GoIV/issues/24#issue-171504177.

And in my limited experience, I've not yet seen candy detection misread the candy name, while I have totally seen pokemon detection screw up.

**Comment by mattaereal** [comment]
On my experiencie I can confirm what @Blaisorblade says.

**Comment by sarav** [comment]
Fixed by #131
