### ISSUE TITLE
Release 3.0.2 with bugfixes?

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#298]
Possible fixes to backport:
- #269
- #243
- Maybe #236 or is that too big?

**Comment by nahojjjen** [comment]
If we release a 3.0.2 I think we need to include a fix for the IV-button not doing anything, and that you cant stop-start to fix it, a lot of people seem to be affected.

**Comment by Blaisorblade** [comment]
That has a high impact, but most of it is in @sarav's big PR and backporting that to 3.0.1 wouldn't make for a stable release. If we want that, we could instead release 3.1.0 ASAP and delegate the new features we want to 3.1.1.

**Comment by leppie** [comment]
Yes, please, the S7 issue is driving me nuts!

**Comment by Blaisorblade** [comment]
@leppie You talk about the IV button or sth. else? Didn't know it was worse on S7.

**Comment by leppie** [comment]
@Blaisorblade The IV button issue. Could not see any errors in logcat. Will try build from source tonight or tomorrow to check.

**Comment by Blaisorblade** [comment]
There won't be anything on logcat, but if you use the online version we get the stack traces, and we think the version on master should fix it—but testing would be good.

BTW we're discussing (in #281) whether to have the errors also on logcat for release builds—I've argued users like you would like that, but you're the first to show up. A debug build will already show errors on logcat.

**Comment by leppie** [comment]
Errors should always show in logcat at least. I understand not wanting to annoy a user with needless dialogs, but a toast would be unintrusive.

**Comment by Blaisorblade** [comment]
The app used to crash in those cases—I fixed the crash but now it gets stuck instead. That wasn't really planned, but since many users now cleanse their phone with fire to restart GoIV maybe crashing is better. (I don't believe it can be necessary to restart the phone to fix this, but maybe killing GoIV is harder than I think).

**Comment by leppie** [comment]
Everything was working fine for me till I today. Even on the latest version. Maybe a caching issue? I did reboot my phone today (which I never do), not sure if that was a factor.

Anyways, if I get time, I will grab code and build tomorrow.

**Comment by Blaisorblade** [comment]
Meanwhile I'm closing this issue since we won't do a 3.0.2.
But @leppie let us know either way. If you see the problem on master please open a new issue.

**Comment by sarav** [comment]
The "Stop" and "Start" should work much better than before. I clear out and reinitialize a lot more stuff than it used to do before. The code is still not where I want it to be, but I hope it's more usable now.

**Comment by leppie** [comment]
@sarav is that on master, or for 3.0.1? I am on the latter, and does not work for me. From Reddit, it appears to be very S7 specific.

**Comment by sarav** [comment]
Master.

**Comment by leppie** [comment]
Confirmed, all is working well so far with an OnlineDebug build from master
