### ISSUE TITLE
Create a new project with the detection code and use it as a dependency

### ISSUE THREAD

**Issue by BraisGabin** [farkam135/GoIV#524]
I move this conversation to a new issue https://github.com/farkam135/GoIV/pull/502#issuecomment-255619556

What do you think about move all the detection code to a separated project? I'll be more than happy to help with that.

Reasons to move the code:

* Easier to test. No UI involved.
* Better for the PoGO community. Other developers in other apps can use it. And they can help with that project too (I'd be the first one).
* Other developers can develop new apps using this "core" project.

I think that two (or more) apps are not a bad idea. Each app has different UI, UX, features, colors... whatever. But the detection part must be the same: Read a Screenshot, guess the hide parts, calculate the iv... that's the difficult work.

**Comment by sarav** [comment]
I'm not opposed to the modularization idea so that other projects can use this code. That's a good thing for an opensource project. If someone comes with a UI that works better for me, I'd be all for it. 

But I'd only contribute to that library if GoIV switched to it -- which is an obvious statement I guess. I want the code I contribute to make the experience better on my device and if GoIV doesn't use the library it won't benefit my device.

Also, thinking more about it, I'm not sure we need a separate project -- it'd be a pain in the ass if I have to switch between projects to fix something I care about. I'd think that Gradle (or whatever Android is the Android build tool) should be able to have a target that spits out a library that other projects could just download and use. We could release it in conjunction with GoIV. GoIV would also be a good example code on how to use the library and a way to test it on devices (in addition to any unit test that run on screenshots).

**Comment by Blaisorblade** [comment]
There's a 👍  from me. I'm not sure which should be the starting point of the detection code, not having reviewed them in detail, but yours has more tests and seems more maintainable. OTOH I'm not sure that we have the time right now to rewire our code to a different module for OCR, or whether you'd be interested...

FWIW, I'd be open to using the pull request hack (http://felixge.de/2013/03/11/the-pull-request-hack.html) and giving you access too — but I'm not sure about the others.

**Comment by nahojjjen** [comment]
I'm not completely sold on the idea. From what I understand, you're suggesting the project should move the OCR logic to a dependency - which would be the methods that extract information from a pokemon image, and detects when you're on a pokemon screen. Please correct me if I understood wrong.

> Easier to test. No UI involved.

What tests do we want to perform on our detection code? Im guessing the getXFromImg methods in OcrHelper, but what would we gain from having tests on those? I suppose the upside would be to test several different screen sizes, but I'm not convinced that will really be of any real help. What I'm really concerned about is the risk that the tests might slow down / made it more difficult to change the ocr logic, without contributing meaningful information.

> Better for the PoGO community. Other developers in other apps can use it. And they can help with that project too (I'd be the first one).

While I agree that it would be a good thing to enable other devs to use the ocr logic, I wonder if a simpler solution would be possible. For example, I'm working on a branch to allow the app Storimod to gain access to the information scanned from GoIV. Currently this works by that GoIV has an "export" button in results, which sends an Intent with string formated json data of the result. If other apps use that, they dont need to use any ocr dependency at all, but can instead just code around catching a json object intent.  I think this works in a pretty clean way with the current goiv code, and should also be simpler for other devs to work with - and if they want other / more information in the json object, that's simple to add.

**Comment by sarav** [comment]
@nahojjjen 

> what would we gain from having tests on those? I suppose the upside would be to test several different screen sizes, but I'm not convinced that will really be of any real help

Unit tests for our detection code would be very valuable. We've had a couple of cases of us breaking things while trying to improve the heuristics -- including PRs that were not merged because someone else pointed it out. Also, we always have to ask people to test it a lot before we merge these changes. Having a collection of screenshots would allow the dev to test it and possibly even have Travis test it. That'd be a huge benefit to speeding up the development process.

> What I'm really concerned about is the risk that the tests might slow down / made it more difficult to change the ocr logic, without contributing meaningful information.

It would actually be the opposite. It would speed up development as I mentioned above. And if we start trying to train tesseract even further, this would be super handy to make sure it didn't make the detection worse for some while making it better for the images that the dev cares about.

> Currently this works by that GoIV has an "export" button in results, which sends an Intent with string formated json data of the result. If other apps use that, they dont need to use any ocr dependency at all ...

You are assuming other apps want to use the same UI as GoIV though. That might not be true at all. There are plenty of different UIs for some of the IV apps that I think there's some justification for that use case. Sure, they'd start competing with GoIV, but I don't think that matters -- competition is good.

But I'd prefer it to be a single git project so that it's not a pain in the neck for GoIV devs.

**Comment by BraisGabin** [comment]
First of all I think that Ninactic gave us a new good reason to make this project in the last update:

* Don't fix the HP problem twice.

> But I'd only contribute to that library if GoIV switched to it -- which is an obvious statement I guess. I want the code I contribute to make the experience better on my device and if GoIV doesn't use the library it won't benefit my device.

If GoIV doesn't use it I think that you, the devs, probably wont work on that project neighther. Anyway I understand that this is a big refactor.

> While I agree that it would be a good thing to enable other devs to use the ocr logic, I wonder if a simpler solution would be possible. For example, I'm working on a branch to allow the app Storimod to gain access to the information scanned from GoIV. Currently this works by that GoIV has an "export" button in results, which sends an Intent with string formated json data of the result. If other apps use that, they dont need to use any ocr dependency at all, but can instead just code around catching a json object intent. I think this works in a pretty clean way with the current goiv code, and should also be simpler for other devs to work with - and if they want other / more information in the json object, that's simple to add.

You are forcing to use GoIV to the users. Since there's nothing wrong with that, I think that some users/developers prefer to have more options. An example: [storimod](https://www.reddit.com/r/pokemongodev/comments/58drd6/implementation_storim%C3%B5d_pvp_battle_system_social)

--

About tests

I think that the tests speeds up the development. My app has a feature, the user can email me with the screenshots that PokeScreenshot didn't detect correctly. I add that screenshot to my collection and fix the problem. Toons of times fix one problem brokes other. The good thing here is that I notice that because some test stop working. And if I don't have a test that checks that it's not a big deal. I'll receive a new screenshot with the new problem.

Down sides: my collection right now is nealy useless. The new UI is the reason.

--

About how to use the external projects and other solutions

My initial idea with PokeScreenshot was to have two projects. PokeScreenshot and this *core* project that I'm talking about here. At the beggining (and until now) it's just a module inside my project, not a different repo.

There's lots of ways to do this.

* Submodules. [Internal Library Dependency Management by Kelly Shuster](https://youtu.be/EsOTPNAaH6o).
* https://jitpack.io/
* Symlinks
* Even a module in this repo would be ok. At least as a transition state.

Anyway I don't know how you works, but in my code I have very few commits were I change the OCR part and the UI at the same time. I mean, they are very different problems. My idea is create an interface, somthing like this: [ScreenshotReader](https://github.com/BraisGabin/pokescreenshot/blob/master/processing/src/main/java/com/braisgabin/pokescreenshot/processing/ScreenshotReader.java). If your problem is the detection, you must fix the *core*. If your error is outside, you must fix GoIV.

--

I think that this *core* project (I don't know how to name it) can have different more things than the OCR. Color detection to fix nidoran, the iv formulas, the level detection (reading the arc), a guesser to know which pokémon are we looking at, etc.

Different "pieces" of code. The app is the one who decide how to use them.

**Comment by Blaisorblade** [comment]
@BraisGabin I totally agree on testing, even though I'll confess I'm often too lazy to write them (but I'd do it if we agreed on it). Not proud of that ;-).

And I also agree on possibly sharing the backend for more features, step by step.

> Down sides: my collection right now is nealy useless. The new UI is the reason.

Well, the changes are annoying for both of us, but at least you can easily collect new screenshots.

> https://jitpack.io/

That might work once the interface is stable...

> Submodules.

That would technically work, but I fear it's a significant barrier to contributions. (Disclaimer: I have a basic idea but I never learned to use them properly, *because* most people mentioning submodules made similar arguments).

> Symlinks

Would not work well on Windows.

> Even a module in this repo would be ok. At least as a transition state.

👍  Given the only admin in this repo is currently rather busy with life, we might want to migrate to a fork. We'd just need to agree on technical privileges and social conventions (say, share commit access, use code review, which automatic checks to have, and such things). And the GUIs could keep having different teams.

**Comment by Blaisorblade** [comment]
> And the GUIs could keep having different teams.

Meaning: a shared repo doesn't mean your changes to Pokeassistant have to be accepted by our team, or viceversa ;-) We have very different GUIs after all. (Though of course we can still discuss together).

Note: I'm away traveling next week, so I'd lack the time to actually set this up quickly—but we'd first need to agree on things. (And probably GoIV should do a release beforehand with the new features/changes).

**Comment by nahojjjen** [comment]
Seems most people here like the idea of splitting the project.
I'm still against it, but democracy seems to be working against me, so I'm fine if the change goes though.

If we're opening a new repo for the "ocr/image recognition core", I suggest Blaisorblade starts the new repo, he's consistently shown that he's good with git & he's a major GoIV project contributor.

**Comment by BraisGabin** [comment]
I think that an organization is the best option here. And I think that @Blaisorblade can create it and be the owner to manage it. 

@nahojjjen as soon as you can check your code without the phone you love the tests. I fixed  the new Pokémon GO interface without run my app any time. But I agree that write them is a pain. 

And I agree, we must talk about how to do this. It's not trivial. The biggest difference between both base codes are the use of Optional vs Exceptions. And that's a big difference, I think.

How do you want to do this? This issue? Create different issues? Wait for a repo to create them there?

**Comment by Blaisorblade** [comment]
Thanks for the trust. So we have some general consensus. I wasn't sure about the details, but I went ahead, picked a third name (PoGoTools) and created https://github.com/PoGoTools/PoGoTools. You should all have been invited—some as owners, some as admins. I also invited as devs other contributors, as I've been meaning to do for a while (http://felixge.de/2013/03/11/the-pull-request-hack.html). Lots of the choices were very ad-hoc—mostly, I didn't invite as admins people we hadn't agreed on this plan with, but I'm happy to add privileges to contributors.

I wouldn't switch to the new repo yet while we figure out how to best do that (I'd like to try and import both histories since I do use history to track down bugs), but meanwhile we do have a repo (and we can at least create issues there).

Also, I think we want to do a release before switching to the repo and it'll take us a small while, and I'm not sure how to manage our project meanwhile. Probably we want to branch the repo anyway.

-------

Regarding choices: we can open issues on the new repo, but let me answer re Optional vs Exceptions.
Crucially, GoIV goes ahead *and produces a scan result* even if it fails detecting some field (say, HP), unlike Pokescreenshot. What does one store as HP? Either use `Optional`, or `null`, or something like `-1` — I wouldn't store an exception. `null` doesn't work for raw `int` (you need `Integer`) and forces you to risk NullPointerExceptions. `-1` means carefully branching on each use. Given my experience in functional programming I picked `Optional` instead. One downside is that most other GoIV devs appear unfamiliar with it, but at least they've not complained about it. 😅 
What's left to pick is how to propagate failures produced as return values: you can also using `Optional` is most consistent, assuming the exception isn't relevant. If the exception value matters, something like `Either<Exception, Integer>` would work if you know what I mean, except Guava doesn't provide it. Or you can use exceptions, and later catch exceptions and produce `Optional.absent()`. The second seems more cumbersome but would work, though I suspect failures are too common for exceptions.

**Comment by sarav** [comment]
@nahojjjen I don't think I ever said we should actually split the project. I'm just proposing we release the "OCR" (all the other image handling, etc) component as a library along with GoIV.

@Blaisorblade I understand if we need to fork if @farkam135 is busy and not able to manage granting commit rights, etc. I think that's what you greated PoGoTools for,.

But I still don't see the need to split out the "OCR" code. So, before we go ahead and start making the transitions, can we please discuss what exactly we are going to do? For the amount of git I use at work, I've surprisingly not had to deal with modules or submodules. But I think they are still cumbersome for GoIV. I just want to sync one tree.

@BraisGabin Yes, we don't often have to touch the OCR code and the UI at the same time. But there have been and always will be cases where changing the OCR code will force some changes on the UI related code. For example, say we switch from Option to Exception. Now all the UI code that calls the OCR library has to deal with this API change. If I have two git repos to sync, I now have to tag and make  sure they are synced up to the right amount to make builds.

Another way to look at this is to think of GoIV as a unit test for the OCR library. It's a good way to make sure any changes we are making isn't breaking the users. Unless I can see a strong argument against just releasing .jar libraries from GoIV repo, I'd prefer we don't split this into multiple git repos (this includes modules because AFAIK, they have their own separate HEADs).

**Comment by Blaisorblade** [comment]
> For the amount of git I use at work, I've surprisingly not had to deal with modules or submodules. But I think they are still cumbersome for GoIV. I just want to sync one tree.

I think there's a misunderstanding and I agree with you @sarav; there's little support for `git submodule`, I don't think that "git modules" exist; I've used "module" in the "part of code" sense (as in modular).

Concretely, I'd like at first to simply have both projects in a repo in two folders, and refactor them incrementally to share code.

And as you say, one *can* change the API of shared code and of the clients (and tests) in one commit; any changes that don't affect the API would only need touch the relevant module.

**Comment by BraisGabin** [comment]
I think that you GoIV doesn't have the need to split the code. My app neither. I think that the main idea is create code that third devs can use while we improve our own code. That's the point of an open source library

Other good thing is that other devs can help with this new project because it's smaller and, for that reason, easier to modify.

But I think that, in short, GoIV will not be better for this change. Nor worst.

--

Optional vs Exceptions

My approach is a bit pythonic, I think. As you pointed out the pros of Exceptions is that you know which was the problem. For me this is crucial because I take decisions about what to try next using this exceptions (I don't just crash or show an "impossible to read" message).

But reading your comment I agree that Optional are really handy. Probably we can have two layers. The deeper layer throws exceptions. You can use it if you want to mess with them. The second layer use the first layer and change the exception model to a optional model. Easier to handle.

--

I think that a gradle module is a great idea to start the split process. All the code is in the same repo but you can see the division perfectly. I use this approach in my app.

**Comment by Blaisorblade** [comment]
> But I think that, in short, GoIV will not be better for this change. Nor worst.

I'm hoping that also GoIV will be better overall — if nothing else because of having one more contributor, at least to the shared code.

---

> But reading your comment I agree that Optional are really handy. Probably we can have two layers. The deeper layer throws exceptions. You can use it if you want to mess with them. The second layer use the first layer and change the exception model to a optional model. Easier to handle.

That idea sounds reasonable, but if you only use exceptions to show causes, using something like `Either` might do the job without needing the translation. Should I say more about how `Either` works, or are you familiar with it?

Anyway, we can move this discussion to an issue on the new repo...

**Comment by Blaisorblade** [comment]
OK, so I managed to merge the repos there. For now this is an experiment, but it should be possible to build each project separately.

To checkout quickly:

```
GIT_LFS_SKIP_SMUDGE=1 git clone git@github.com:PoGoTools/PoGoTools.git
git lfs pull
```

As soon as everybody here can checkout that repo and is fine with the merge, GoIV devs can move development there. I'd expect this could already work for @BraisGabin. The actual merging can happen more slowly with the needed time.

If new commits are done here, it should even be possible to move them there with one command. I'll probably have to try this soon, I don't want to bother submitters of existing PRs with all this.

I'd guess GoIV wants a release branch, so we can do a release with the current code (modulo fixes).

I'm no Gradle expert, so I'd leave the Gradle changes to somebody else — @BraisGabin seems to already have an idea of what to do.

**Comment by Blaisorblade** [comment]
BTW, details on what I did are in https://github.com/PoGoTools/PoGoTools/issues/2, I expect at least @sarav might care, and other Git experts as well.

That also discusses a bit Git LFS (https://git-lfs.github.com/) which is required for the checkout (sorry I didn't mention that above); without Git LFS the cloning will fail.

**Comment by sarav** [comment]
@Blaisorblade  Ok, I'm super busy till Saturday noon. Have a bit of a free time and then busy till Sunday noon and then I have to travel for a week from Monday. So, maybe at least wait for me to try out the new repo till Monday morning Europe time. I'll try to squeeze it is.

Also, what's up wit the GIT_LFS_SKIP_SMUDGE? What happens if I just do a normal git clone? I've never use LFS. Is that the one for storing binary files efficiently?

**Comment by BraisGabin** [comment]
I think that we can close this issue and move all the topics to the new repo: https://github.com/PoGoTools/PoGoTools/

I created a new issue to talk about Optional and Exceptions: https://github.com/PoGoTools/PoGoTools/issues/3
